### ISSUE TITLE
api eth_getTransactionReceipt aways return fixed contractAddress "0x6295ee1b4f6dd65047762f924ecd367c17eabf8f"

### ISSUE THREAD

**Issue by nowto** [DSiSc/apigateway#48]
**Describe the bug**
when invoke eth_getTransactionReceipt api to get contractAddress, it aways return fixed contractAddress “0x6295ee1b4f6dd65047762f924ecd367c17eabf8f”， no matter which deploy contract transaction.

**Comment by DanielCormier1** [comment]
has fixed
