### ISSUE TITLE
An error has occured on the balance of the address.

### ISSUE THREAD

**Issue by luyantinglyt** [DSiSc/apigateway#49]
**Describe the bug**
The balance of address A is 10w, the balance of address B is 0. After api eth_sendTransaction, the balance of A is 9.01w, the balance of B is 1w.
The balance of the address error.

**To Reproduce**

```
json
{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from": "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b","to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567","gas": "0x64","gasPrice": "0x1","value": "0xDE0B6B3A7640000"}],"id":1}
```

**Expected behavior**
The balance of A is 8.9w.

**Comment by DanielCormier1** [comment]
has fixed

**Comment by luyantinglyt** [comment]
Now, there ISN'T the gas loss when u transfer accounts.
