### ISSUE TITLE
The ratio of gas and value is 1:1.

### ISSUE THREAD

**Issue by luyantinglyt** [DSiSc/apigateway#50]
**Describe the bug**
The ratio of  gas and value is 1:10^18 in ethereum.

**To Reproduce**

The ratio of gas and value is 1:1.But the ratio of  gas and value is 1:10^18 in ethereum.

**Expected behavior**
The ratio of  gas and value is 1:10^18 .

**Comment by DanielCormier1** [comment]
not bug, this is a config of justitia, we will not modify it now
